### ISSUE TITLE
Accelerate-examples fails to build with CUDA

### ISSUE THREAD

**Issue by Athas** [AccelerateHS/accelerate#357]
Using the current Git HEAD of accelerate-examples:

```
$ STACK_YAML=stack-8.0.yaml stack install --flag=accelerate-examples:cuda
Getting project config file from STACK_YAML environment
Cabal file warning in /home/athas/accelerate-examples/.stack-work/downloaded/HOUyjyzRIZEp/llvm-general/llvm-general.cabal: Ignoring unknown section type: custom-setup
Cabal file warning in /home/athas/accelerate-examples/.stack-work/downloaded/HOUyjyzRIZEp/llvm-general/llvm-general.cabal: Ignoring unknown section type: custom-setup
There were multiple candidates for the Cabal entry "Config" (/home/athas/accelerate-examples/examples/smvm/Config.hs), picking /home/athas/accelerate-examples/examples/nofib/Config.hs
There were multiple candidates for the Cabal entry "Main.hs" (/home/athas/accelerate-examples/examples/smvm/Main.hs), picking /home/athas/accelerate-examples/examples/nofib/Main.hs
accelerate-cuda-0.16.0.0: build
Progress: 1/2
--  While building package accelerate-cuda-0.16.0.0 using:
      /home/athas/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.2.0-ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build lib:accelerate-cuda --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/athas/accelerate-examples/.stack-work/logs/accelerate-cuda-0.16.0.0.log

    Preprocessing library accelerate-cuda-0.16.0.0...
    [18 of 35] Compiling Data.Array.Accelerate.CUDA.AST ( Data/Array/Accelerate/CUDA/AST.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/Data/Array/Accelerate/CUDA/AST.o )
    
    /home/athas/accelerate-examples/.stack-work/downloaded/-RcqODB9NkTF/Data/Array/Accelerate/CUDA/AST.hs:152:10: error:
        • Overlapping instances for Show (ExecAfun a)
            arising from a use of ‘GHC.Show.$dmshowsPrec’
          Matching instances:
            instance (accelerate-1.0.0.0:Data.Array.Accelerate.Trafo.Base.Kit
                        acc,
                      PrettyEnv aenv) =>
                     Show (PreOpenAfun acc aenv f)
              -- Defined in ‘Data.Array.Accelerate.Pretty’
            instance Show (ExecAfun a)
              -- Defined at Data/Array/Accelerate/CUDA/AST.hs:152:10
        • In the expression: GHC.Show.$dmshowsPrec @ExecAfun a
          In an equation for ‘showsPrec’:
              showsPrec = GHC.Show.$dmshowsPrec @ExecAfun a
          In the instance declaration for ‘Show (ExecAfun a)’
    
    /home/athas/accelerate-examples/.stack-work/downloaded/-RcqODB9NkTF/Data/Array/Accelerate/CUDA/AST.hs:152:10: error:
        • Overlapping instances for Show (ExecAfun a)
            arising from a use of ‘GHC.Show.$dmshowList’
          Matching instances:
            instance (accelerate-1.0.0.0:Data.Array.Accelerate.Trafo.Base.Kit
                        acc,
                      PrettyEnv aenv) =>
                     Show (PreOpenAfun acc aenv f)
              -- Defined in ‘Data.Array.Accelerate.Pretty’
            instance Show (ExecAfun a)
              -- Defined at Data/Array/Accelerate/CUDA/AST.hs:152:10
        • In the expression: GHC.Show.$dmshowList @ExecAfun a
          In an equation for ‘showList’:
              showList = GHC.Show.$dmshowList @ExecAfun a
          In the instance declaration for ‘Show (ExecAfun a)’
```

Every other dependency builds correctly.  This is on a system with CUDA 8, but I don't think that is the reason.

**Comment by tmcdonell** [comment]
Unfortunately #335: accelerate-cuda does not build with ghc-8.0.2. This is why it is currently disabled in the stack configuration.

Two options:

  * I'd recommend transitioning to `accelerate-llvm-ptx`, it works pretty well at this point, and is "the future". At some point I'll get time to make `accelerate-cuda` build with ghc-8.0.2, but it is unlikely to receive any new features (unless others can help contribute them!).

  * If you still want to use `accelerate-cuda`, change the resolver in the `stack-8.0.yaml` file to something in the 7.x series as that still uses ghc-8.0.1 (7.19 is currently the most recent), and edit the flags section to turn the cuda bits back on (or on the command line as you did above). The other dependencies etc. should all be the same.

**Comment by tmcdonell** [comment]
Oh, one problem with ghc-8.0.1 is [GHC#12573](https://ghc.haskell.org/trac/ghc/ticket/12573), which causes problems for CUDA & OpenCL (you may have run into this as well).

**Comment by Athas** [comment]
Ah, that's unfortunate.  Your advice works for me.
