### ISSUE TITLE
accelerate-cuda-0.15.1.0 and cuda-0.7.0.0 don't seem to play nice

### ISSUE THREAD

**Issue by cpdurham** [AccelerateHS/accelerate#296]
In latest stack resolver lts-4.1 with ghc-7.10.3, did 
`stack ghci accelerate accelerate-cuda-0.15.1.0 cuda-0.7.0.0 mainland-pretty-0.4.1.2 language-c-quote-0.11.4 exception-mtl-0.4 symbol-0.2.4`
and got the error
```
    /tmp/stack6799/accelerate-cuda-0.15.1.0/Data/Array/Accelerate/CUDA/Context.hs:68:43:
        Not in scope: ‘CUDA.setCacheConfig’
        Perhaps you meant ‘CUDA.setCacheConfigFun’ (imported from Foreign.CUDA.Driver)
    
    /tmp/stack6799/accelerate-cuda-0.15.1.0/Data/Array/Accelerate/CUDA/Context.hs:155:57:
        Not in scope: ‘CUDA.useDevice’
        Perhaps you meant one of these:
          data constructor ‘CUDA.Device’ (imported from Foreign.CUDA.Driver),
          data constructor ‘CUDA.NoDevice’ (imported from Foreign.CUDA.Driver),
          ‘CUDA.useDevicePtr’ (imported from Foreign.CUDA.Driver)
```
Not sure if this is intended behavior (where accelerate-cuda-0.15.1.0 is incompatible with cuda-0.7.0.0), but thought it was worth mentioning.

**Comment by zmactep** [comment]
I have the same problem

OS X 10.11.2
GHC 7.10.3 (from `homebrew`)

**Comment by tmcdonell** [comment]
oops. I updated the version bounds for accelerate-cuda-0.15.1.0 on Hackage to reflect that it doesn't work with cuda-0.7.*, and will upload a point release for >= 0.7 shortly.

**Comment by tmcdonell** [comment]
Uploaded [`accelerate-cuda-0.15.1.1`](http://hackage.haskell.org/package/accelerate-cuda-0.15.1.1).

Thanks for the report.
