### PR TITLE
Fix the build with GHC 8.4

### PR DESCRIPTION
**Pull request by RyanGlScott**
A couple of changes are required in order to make `accelerate` build with GHC 8.4:

* Since `Semigroup` has become a superclass of `Monoid`, `Semigroup` instances need to be ~~added~~ in scope in `Data.Array.Accelerate.Data.Monoid`.
* GHC 8.4 [slightly changes the way it reifies GADTs](https://ghc.haskell.org/trac/ghc/wiki/Migration/8.4#TemplateHaskellreificationchangesforGADTs), and as a result, some of the plumbing code in `Data.Array.Accelerate.Classes.ToFloating` and `Data.Array.Accelerate.Classes.FromIntegral` has to be updated, or else you'll end up with an error like:

```
Data/Array/Accelerate/Classes/ToFloating.hs:1:1: error:
    Exception when trying to run compile-time code:
      Unexpected case generating ToFloating instances
CallStack (from HasCallStack):
  error, called at ./Data/Array/Accelerate/Classes/ToFloating.hs:66:21 in accelerate-1.1.1.0-inplace:Data.Array.Accelerate.Classes.ToFloating
    Code: runQ
            $ do let digItOut :: Name -> Q [Name]
                     ....
                 as <- digItOut ''NumType
                 bs <- digItOut ''FloatingType
                 ....
  |
1 | {-# LANGUAGE CPP                   #-}
  | ^
```

### CODE REVIEW

File: src/Data/Array/Accelerate/Data/Monoid.hs [hunk 1]
```diff
@@ -198,3 +198,31 @@ instance (Elt a, Elt b, Elt c, Elt d, Elt e, Monoid (Exp a), Monoid (Exp b), Mon
                 in
                 lift (a1 `mappend` a2, b1 `mappend` b2, c1 `mappend` c2, d1 `mappend` d2, e1 `mappend` e2)
 
+#if __GLASGOW_HASKELL__ >= 800
```
Comment (RyanGlScott) [inline src/Data/Array/Accelerate/Data/Monoid.hs]: I followed the existing convention in this module of conditionally defining `Semigroup` instances using CPP. If you'd prefer, we could axe this CPP by depending on the `semigroups` library for backwards compatibility with versions of GHC older than 8.0.

Comment (RyanGlScott) [reply src/Data/Array/Accelerate/Data/Monoid.hs]: Oops, I just discovered there's a `Data.Array.Accelerate.Data.Semigroup` module which already implements this. In that case, the fix is much simpler: just import that here.

**Comment by tmcdonell** [comment]
Awesome, thanks Ryan! ^_^
