### ISSUE TITLE
Build failure with ghc-8.0.2

### ISSUE THREAD

**Issue by djduke** [AccelerateHS/accelerate#335]
I'm getting an "overlapping instances" error when compiling using GHC HEAD (or at least version 8.1.20161012), see error log below.  On the assumption that the instance in Data.Array.Accelerate.CUDA.AST was intended to be more specific that that from Data.Array.Accelerate.Pretty, I tried to add an OVERLAPPING pragma, but this triggered a further type error in Accelerate.CUDA.CodeGen.Stencil.   I'm aware there have been some changes to the AST to accommodate e.g. deriving strategies; I had to update haskell-src-meta to allow it to compile, but unclear that it has any link with the overlapping issue.   Do you have a successful build of accelerate-cuda on OSX?

regards, David.

```
[18 of 34] Compiling Data.Array.Accelerate.CUDA.AST ( Data/Array/Accelerate/CUDA/AST.hs, dist/build/Data/Array/Accelerate/CUDA/AST.o )

Data/Array/Accelerate/CUDA/AST.hs:152:10: error:
    • Overlapping instances for Show (ExecAfun a)
        arising from a use of ‘GHC.Show.$dmshowsPrec’
      Matching instances:
        instance (accelerate-1.0.0.0:Data.Array.Accelerate.Trafo.Base.Kit
                    acc,
                  PrettyEnv aenv) =>
                 Show (PreOpenAfun acc aenv f)
          -- Defined in ‘Data.Array.Accelerate.Pretty’
        instance Show (ExecAfun a)
          -- Defined at Data/Array/Accelerate/CUDA/AST.hs:152:10
    • In the expression: GHC.Show.$dmshowsPrec @ExecAfun a
      In an equation for ‘showsPrec’:
          showsPrec = GHC.Show.$dmshowsPrec @ExecAfun a
      In the instance declaration for ‘Show (ExecAfun a)’

Data/Array/Accelerate/CUDA/AST.hs:152:10: error:
    • Overlapping instances for Show (ExecAfun a)
        arising from a use of ‘GHC.Show.$dmshowList’
      Matching instances:
        instance (accelerate-1.0.0.0:Data.Array.Accelerate.Trafo.Base.Kit
                    acc,
                  PrettyEnv aenv) =>
                 Show (PreOpenAfun acc aenv f)
          -- Defined in ‘Data.Array.Accelerate.Pretty’
        instance Show (ExecAfun a)
          -- Defined at Data/Array/Accelerate/CUDA/AST.hs:152:10
    • In the expression: GHC.Show.$dmshowList @ExecAfun a
      In an equation for ‘showList’:
          showList = GHC.Show.$dmshowList @ExecAfun a
      In the instance declaration for ‘Show (ExecAfun a)’
```

**Comment by tmcdonell** [comment]
This might be a result of https://ghc.haskell.org/trac/ghc/ticket/12881.

Adding an `{-# OVERLAPS #-}` pragma or similar allows it to proceed, but it falls over later with a different error. More investigation required...

**Comment by tmcdonell** [comment]
(tested with ghc-8.0.2-rc1)

**Comment by tmcdonell** [comment]
I will note that both `accelerate-llvm-native` and `accelerate-llvm-ptx` work fine with ghc-8.0.2-rc1, so now might be a good time to think about switching... :wink:

**Comment by tmcdonell** [comment]
closing as `accelerate-cuda` has been deprecated.
